### PR TITLE
Have the server return first & last name in the format expected by

### PR DESCRIPTION
**Pull request by andrewlo**
the client so that the name is displayed on the top right of the
app when the user is logged in.

### CODE REVIEW

**Comment by andrewlo** [comment]
@SethDavenport

**Comment by SethDavenport** [comment]
@andrewlo : LGTM. Does this also happen in the typescript-react-redux-starter, react-redux-starter, and angular-redux-starter?

**Comment by andrewlo** [comment]
@SethDavenport 

- angular-redux-starter: issue is not there because they way the login success action is dispatched changes assigns the payload differently
- typescript-react-redux-starter: same issue exists, created PR here: https://github.com/rangle/typescript-react-redux-starter/pull/172
- react-redux-starter: does not have this issue

**Comment by SethDavenport** [comment]
Thanks, :shipit:

**Pull request merged**
