### PR TITLE
Upgrade to angular2.0.0-beta6 and implement required typings

### PR DESCRIPTION
**Pull request by nikolasleblanc**

### CODE REVIEW

**Comment by nikolasleblanc** [comment]
Need to update zonejs dep. Will do soon, headed home.

**Comment by nikolasleblanc** [comment]
Zone.js dependency updated. Tests passed.

**Comment by SethDavenport** [comment]
not sure if requirjs typing are the correct ones - since this is a web pack project, when we use `require` it's essentially the nodejs version.  Can you try `typings install --save --ambient node` instead?

**Comment by nikolasleblanc** [comment]
Good point. Will give that a shot and resubmit.

**Comment by nikolasleblanc** [comment]
Switched and worked. Good catch.

**Comment by SethDavenport** [comment]
:shipit:  - thanks.

**Pull request merged**
