### PR TITLE
All files mapped properly with coverage on require'd files

### PR DESCRIPTION
**Pull request by JaKXz**
https://circle-artifacts.com/gh/rangle/angular2-redux-starter/490/artifacts/0/home/ubuntu/angular2-redux-starter/coverage/lcov-report/index.html

Really close to having proper coverage numbers - now we just need to be able to load all source files into karma so istanbul can instrument them all. Otherwise:

- ~~use `concurrently` for the lint commands~~
- add an `.istanbul.yml` which tells us what configuration istanbul is running with (just add `verbose: true` to the top of the file [edit: for debugging purposes])
- remove unnecessary sourcemap packages [since `remap-istanbul` was fixed to read inline sourcemaps properly in v0.6.3+]
- update `karma-jasmine`
- don't use sourcemaps in production

Caveats:

- `npm run test:report` only works as the `posttest` script, not on its own since the `./coverage/report/coverage-final.json` originally produced by `karma-coverage` is removed
  - it's removed because `istanbul report` pulls all the `.json` files in the `./coverage` folder and screws up the report with the unmapped `.ts` files.

Connected to rangle/rangle-starter#12.

### CODE REVIEW

**Comment by SethDavenport** [comment]
HI @JaKXz thanks for the PR

Mostly looks good. However doesn't using `concurrently` with the various linters cause the output to get all jumbled up?

**Comment by JaKXz** [comment]
@SethDavenport it prefixes the output with the index of the task that's running, so it's pretty easy to pick out where the problem was. Also, it's set to fail fast, so there won't be much output to parse through. 

The idea is that CI runs linting really quick, and if developers need to see each task's output then they can just fire them off manually :)

**Comment by SethDavenport** [comment]
Yeah I'm just not sold on the concurrently thing.

**Comment by JaKXz** [comment]
@SethDavenport done, just for you. :)

**Comment by SethDavenport** [comment]
Cool thanks. @clbond how does this fit with the work you've been doing? If it can coexist let me know and I'll merge it.

**Comment by clbond** [comment]
Ah, embarrassingly enough I already fixed this and it's been merged to master. So I don't think this one is necessary. I'm sorry, I didn't know anyone else was working on this.

**Comment by clbond** [comment]
If you do a clean checkout of master and run mom test you should already see correct numbers and the duplicate files removed from the report. Unless this PR does some other stuff besides that..

**Comment by clbond** [comment]
Heh, not mom test, npm test. Autocorrect :P

**Comment by JaKXz** [comment]
No need to apologize @clbond, thanks for taking care of it!

**Pull request closed without merging**
