### PR TITLE
Feat typed records [NOT MERGE]

### PR DESCRIPTION
**Pull request by danielfigueiredo**
@SethDavenport @e-schultz 
First attempt of the TypedRecord structure, it replaces the transformers and it provides typed return types for all immutable Map functions.
Let me know your thoughts

### CODE REVIEW

**Comment by danielfigueiredo** [comment]
Not sure why tests are failing they are passing in my local environment

**Comment by SethDavenport** [comment]
Looking mostly good. I'm still hoping there's a way to decouple making the TypedRecord constructor from instantiating an actual record though.

So I can do something like:

```typescript
interface IPerson {
  name: string;
};

interface IPersonRecord extends TypedRecord<IPersonRecord>, IPerson {};

// Oh noes! It is literally a factoryfactory.
const PersonRecord = makeRecordType<IPerson, IPersonRecord>({
        name: '',
});

const vader = PersonRecord({ name: 'Darth Vader' });
const binks = PersonRecord({ name: 'Jar-Jar Binks' });
const hutt = PersonRecord({ name: 'Jabba the Hutt' });
const poutyFace = PersonRecord({ name: 'Kylo Ren' });
```

**Comment by danielfigueiredo** [comment]
@SethDavenport Finally got what you wanted working, problem was to make the object you send down into `PersonRecord({...})` be validated at compile time to be a Person.
Lots of hacks to make that possible.
@bennett000 this is the PR to use that in our starter. 
If we're really going to make an NPM module out of this do you think we should include this either way or do the module first and then use the module here?

**Comment by danielfigueiredo** [comment]
I'm closing this PR for now while the NPM [module](https://github.com/rangle/typed-immutable-record) is published. Then I will resume the work in this PR to use that library instead.

**Pull request closed without merging**
